from . import shippingbo_api
from . import sale_order
from . import res_config_settings
from . import shippingbo_carrier_mapping
from . import stock_move
from . import stock_warehouse
from . import stock_picking
from . import stock_picking_capsule
from . import stock_picking_return
from . import purchase_order
from . import product_template
from . import product_product
