{
    "name": "ShippingBo Connector",
    "version": "19.0.2.0.0",
    "summary": "Deliveries, purchase receipts, returns, products and stock synced between Odoo and ShippingBo",
    "author": "Stanislas Badatcheff",
    "website": "https://catalyt.fr",
    "license": "OPL-1",
    "category": "Inventory",
    "depends": ["stock", "sale", "sale_stock", "delivery", "stock_delivery", "purchase_stock"],
    "data": [
        "security/ir.model.access.csv",
        "views/shippingbo_carrier_mapping_views.xml",
        "views/res_config_settings_views.xml",
        "views/stock_picking_views.xml",
        "views/product_template_views.xml",
        "views/stock_warehouse_views.xml",
        "data/stock_sync_cron.xml",
        "data/product_sync_cron.xml",
        "data/capsule_poll_cron.xml",
        "data/log_purge_cron.xml",
    ],
    "images": ["static/description/icon.png"],
    "price": 349.0,
    "currency": "EUR",
    "installable": True,
    "application": False,
    "auto_install": False,
}
